/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewRanking.java
 *
 * Created on Nov 11, 2011, 10:43:39 PM
 */
package client.View;

import model.Rank;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SizeSequence;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Trung Hoang
 */
public class JDialogRanking extends javax.swing.JDialog {

    /** Creates new form ViewRanking */
    public JDialogRanking() {
        initComponents();
    }

    public JDialogRanking(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabedRank = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableEasy = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMedium = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableHard = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableHardest = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ranking");
        setBounds(new java.awt.Rectangle(300, 250, 0, 0));
        setResizable(false);

        jTabedRank.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabedRank.setPreferredSize(new java.awt.Dimension(450, 450));

        jTableEasy.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTableEasy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableEasy.setDragEnabled(true);
        jTableEasy.setGridColor(new java.awt.Color(255, 255, 255));
        jTableEasy.setName("Easy"); // NOI18N
        jTableEasy.setPreferredSize(new java.awt.Dimension(250, 250));
        jTableEasy.setRowHeight(25);
        jScrollPane5.setViewportView(jTableEasy);

        jTabedRank.addTab("Easy", jScrollPane5);

        jTableMedium.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTableMedium.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableMedium.setGridColor(new java.awt.Color(255, 255, 255));
        jTableMedium.setName("Easy"); // NOI18N
        jTableMedium.setPreferredSize(new java.awt.Dimension(250, 250));
        jTableMedium.setRowHeight(25);
        jScrollPane2.setViewportView(jTableMedium);

        jTabedRank.addTab("Medium", jScrollPane2);

        jTableHard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableHard.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTableHard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableHard.setGridColor(new java.awt.Color(255, 255, 255));
        jTableHard.setName("Easy"); // NOI18N
        jTableHard.setPreferredSize(new java.awt.Dimension(250, 250));
        jTableHard.setRowHeight(25);
        jScrollPane3.setViewportView(jTableHard);

        jTabedRank.addTab("Hard", jScrollPane3);

        jTableHardest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableHardest.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTableHardest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableHardest.setGridColor(new java.awt.Color(255, 255, 255));
        jTableHardest.setName("Easy"); // NOI18N
        jTableHardest.setPreferredSize(new java.awt.Dimension(250, 250));
        jTableHardest.setRowHeight(25);
        jScrollPane4.setViewportView(jTableHardest);

        jTabedRank.addTab("Hardest", jScrollPane4);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ranking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTabedRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jTabedRank, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-508)/2, (screenSize.height-464)/2, 508, 464);
    }// </editor-fold>//GEN-END:initComponents
    public String Converttime(int Time) {
        int H = Time / 3600;
        int M = (Time - (3600 * H)) / 60;
        int S = (Time - (3600 * H) - (60 * M));
        String hh = String.valueOf(H);
        if (H < 10) {
            hh = "0" + String.valueOf(H);
        }
        String mm = String.valueOf(M);
        if (M < 10) {
            mm = "0" + String.valueOf(M);
        }
        String ss = String.valueOf(S);
        if (S < 10) {
            ss = "0" + String.valueOf(S);
        }
        return hh + ":" + mm + ":" + ss;
    }

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

    public void showRank(int index, Rank[] easy, Rank[] medium, Rank[] hard, Rank[] hardest) {
        Vector rowHeader = new Vector();
        rowHeader.add("Rank");
        rowHeader.add("Player");
        rowHeader.add("Time average");

        Vector rowData;

        if (index < 0) {
            index = 0;
        }
        jTabedRank.setSelectedIndex(index);

        DefaultTableModel modelEasy = new DefaultTableModel(rowHeader, 0);
        for (int i = 0; i < easy.length; i++) {
            rowData = new Vector();
            rowData.add(i + 1);
            rowData.add(easy[i].getFullname());
            rowData.add(Converttime(easy[i].getTime_average()));
            modelEasy.addRow(rowData);
        }
        jTableEasy.setModel(modelEasy);

        DefaultTableModel modelMedium = new DefaultTableModel(rowHeader, 0);
        for (int i = 0; i < medium.length; i++) {
            rowData = new Vector();
            rowData.add(i + 1);
            rowData.add(medium[i].getFullname());
            rowData.add(Converttime(medium[i].getTime_average()));
            modelMedium.addRow(rowData);
        }
        jTableMedium.setModel(modelMedium);

        DefaultTableModel modelHard = new DefaultTableModel(rowHeader, 0);
        for (int i = 0; i < hard.length; i++) {
            rowData = new Vector();
            rowData.add(i + 1);
            rowData.add(hard[i].getFullname());
            rowData.add(Converttime(hard[i].getTime_average()));
            modelHard.addRow(rowData);
        }
        jTableHard.setModel(modelHard);

        DefaultTableModel modelHardest = new DefaultTableModel(rowHeader, 0);
        for (int i = 0; i < hardest.length; i++) {
            rowData = new Vector();
            rowData.add(i + 1);
            rowData.add(hardest[i].getFullname());
            rowData.add(Converttime(hardest[i].getTime_average()));
            modelHardest.addRow(rowData);
        }
        jTableHardest.setModel(modelHardest);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JDialogRanking().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabedRank;
    private javax.swing.JTable jTableEasy;
    private javax.swing.JTable jTableHard;
    private javax.swing.JTable jTableHardest;
    private javax.swing.JTable jTableMedium;
    // End of variables declaration//GEN-END:variables
}
