package client.View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import client.LookAndFeel;
import client.View.JDialogAbout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionListener;
import javax.print.event.PrintJobEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Board;
import model.Cell;

/**
 * 
 * @author dangth
 */
public class SudokuView extends javax.swing.JFrame {

	/**
	 * Creates new form SudokuView
	 */
	private final int ROW = 9;
	private final int COL = 9;
	private Cell[][] cell;
	private Board matrix;
	private JPanel[][] pl;

	public SudokuView() {
		initComponents();
		// new LookAndFeel();
		plCenter.setSize(new Dimension(646, 559));
		plCenter.setLayout(new GridLayout(3, 3));
		this.setLocationRelativeTo(null);
		// Add Panel (3,3)
		pl = new JPanel[3][3];
		for (int i = 0; i < 3; i++) {
			for (int j = 0; j < 3; j++) {
				pl[i][j] = new JPanel(new GridLayout(3, 3));
				pl[i][j].setBorder(BorderFactory.createLineBorder(
						Color.DARK_GRAY, 2));
				pl[i][j].setVisible(true);
				plCenter.add(pl[i][j]);
			}
		}
		// Add Cell
		cell = new Cell[ROW][COL];
		formatcell(cell);
		for (int i = 0; i < ROW; ++i) {
			for (int j = 0; j < COL; ++j) {
				pl[i / 3][j / 3].add(cell[i][j]);
			}
		}
		plCenter.setEnabled(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		plTop = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		lbUsername = new javax.swing.JLabel();
		lbTime = new javax.swing.JLabel();
		plRight = new javax.swing.JPanel();
		btnNewgame = new javax.swing.JButton();
		btnPause = new javax.swing.JButton();
		btnBack = new javax.swing.JButton();
		BtnRedo = new javax.swing.JButton();
		btnSave = new javax.swing.JButton();
		btnLoad = new javax.swing.JButton();
		btnRank = new javax.swing.JButton();
		btnLevel = new javax.swing.JButton();
		btnTheme = new javax.swing.JButton();
		btnAbout = new javax.swing.JButton();
		plCenter = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		itemNewGame = new javax.swing.JMenuItem();
		itemLoadGame = new javax.swing.JMenuItem();
		itemSaveGame = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JPopupMenu.Separator();
		itemUndo = new javax.swing.JMenuItem();
		itemRedo = new javax.swing.JMenuItem();
		jSeparator3 = new javax.swing.JPopupMenu.Separator();
		itemQuit = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		itemSignup = new javax.swing.JMenuItem();
		itemSignin = new javax.swing.JMenuItem();
		itemSignOut = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		itemTheme = new javax.swing.JMenuItem();
		jMenu6 = new javax.swing.JMenu();
		itmDifficulty = new javax.swing.JMenuItem();
		itemRanking = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		itemHelp = new javax.swing.JMenuItem();
		itemRegister = new javax.swing.JMenuItem();
		itemUpdate = new javax.swing.JMenuItem();
		jSeparator2 = new javax.swing.JPopupMenu.Separator();
		ItemAbout = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Game Sudoku - Dang_Org");
		setResizable(false);

		plTop.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/user64.png"))); // NOI18N

		lbUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		lbUsername.setForeground(new java.awt.Color(255, 0, 0));
		lbUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		lbUsername.setText("Guest");

		lbTime.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
		lbTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbTime.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/clock.png"))); // NOI18N
		lbTime.setText("00.00.00");
		lbTime.setBorder(javax.swing.BorderFactory.createTitledBorder("Time"));

		javax.swing.GroupLayout plTopLayout = new javax.swing.GroupLayout(plTop);
		plTop.setLayout(plTopLayout);
		plTopLayout
				.setHorizontalGroup(plTopLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								plTopLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												lbUsername,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												338,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												119, Short.MAX_VALUE)
										.addComponent(
												lbTime,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												186,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		plTopLayout.setVerticalGroup(plTopLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						plTopLayout
								.createSequentialGroup()
								.addContainerGap(16, Short.MAX_VALUE)
								.addComponent(lbUsername,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										38,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(26, 26, 26))
				.addGroup(
						plTopLayout
								.createSequentialGroup()
								.addComponent(jLabel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						plTopLayout
								.createSequentialGroup()
								.addContainerGap()
								.addComponent(lbTime,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap()));

		plRight.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		btnNewgame.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/NewGame2.png"))); // NOI18N
		btnNewgame.setToolTipText("New Game");

		btnPause.setBackground(new java.awt.Color(255, 255, 255));
		btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/Pause.png"))); // NOI18N
		btnPause.setToolTipText("Pause");
		btnPause.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
		btnPause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

		btnBack.setBackground(new java.awt.Color(255, 255, 255));
		btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/Undo2.png"))); // NOI18N
		btnBack.setToolTipText("Undo");
		btnBack.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
		btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		BtnRedo.setBackground(new java.awt.Color(255, 255, 255));
		BtnRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/Redo2.png"))); // NOI18N
		BtnRedo.setToolTipText("Redo");
		BtnRedo.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
		BtnRedo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

		btnSave.setBackground(new java.awt.Color(255, 255, 255));
		btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/Save3.png"))); // NOI18N
		btnSave.setToolTipText("Save Game");
		btnSave.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
		btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		btnLoad.setBackground(new java.awt.Color(255, 255, 255));
		btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/Load3.png"))); // NOI18N
		btnLoad.setToolTipText("Load Game");
		btnLoad.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
		btnLoad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnLoad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		btnRank.setBackground(new java.awt.Color(255, 255, 255));
		btnRank.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/Ranking2.png"))); // NOI18N
		btnRank.setToolTipText("Ranking");
		btnRank.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
		btnRank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnRank.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		btnLevel.setBackground(new java.awt.Color(255, 255, 255));
		btnLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/level2.png"))); // NOI18N
		btnLevel.setToolTipText("Difficulty");
		btnLevel.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
		btnLevel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

		btnTheme.setBackground(new java.awt.Color(255, 255, 255));
		btnTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/themes2.png"))); // NOI18N
		btnTheme.setToolTipText("Theme");
		btnTheme.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
		btnTheme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

		btnAbout.setBackground(new java.awt.Color(255, 255, 255));
		btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/About.png"))); // NOI18N
		btnAbout.setToolTipText("About Us");
		btnAbout.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
		btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

		javax.swing.GroupLayout plRightLayout = new javax.swing.GroupLayout(
				plRight);
		plRight.setLayout(plRightLayout);
		plRightLayout
				.setHorizontalGroup(plRightLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								plRightLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												plRightLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																btnPause,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																52,
																Short.MAX_VALUE)
														.addComponent(
																btnBack,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																BtnRedo,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btnSave,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btnLoad,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btnRank,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btnLevel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btnTheme,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btnAbout,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btnNewgame,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																0,
																Short.MAX_VALUE))
										.addContainerGap()));
		plRightLayout
				.setVerticalGroup(plRightLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								plRightLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(btnNewgame)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												btnLevel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												btnPause,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(30, 30, 30)
										.addComponent(
												btnBack,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												BtnRedo,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(29, 29, 29)
										.addComponent(
												btnSave,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												btnLoad,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(30, 30, 30)
										.addComponent(
												btnRank,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												btnTheme,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												28, Short.MAX_VALUE)
										.addComponent(
												btnAbout,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		plCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		javax.swing.GroupLayout plCenterLayout = new javax.swing.GroupLayout(
				plCenter);
		plCenter.setLayout(plCenterLayout);
		plCenterLayout.setHorizontalGroup(plCenterLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 642,
				Short.MAX_VALUE));
		plCenterLayout.setVerticalGroup(plCenterLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel2.setText("Copyright@2013 by Dang_Org");

		jMenuBar1.setToolTipText("");

		jMenu1.setText("File");

		itemNewGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_N,
				java.awt.event.InputEvent.CTRL_MASK));
		itemNewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/newgame.png"))); // NOI18N
		itemNewGame.setText("New Game");
		jMenu1.add(itemNewGame);

		itemLoadGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_L,
				java.awt.event.InputEvent.CTRL_MASK));
		itemLoadGame.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/Load.png"))); // NOI18N
		itemLoadGame.setText("Load Game");
		jMenu1.add(itemLoadGame);

		itemSaveGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_S,
				java.awt.event.InputEvent.CTRL_MASK));
		itemSaveGame.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/Save.png"))); // NOI18N
		itemSaveGame.setText("Save Game");
		jMenu1.add(itemSaveGame);
		jMenu1.add(jSeparator1);

		itemUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_Z,
				java.awt.event.InputEvent.CTRL_MASK));
		itemUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/undo.png"))); // NOI18N
		itemUndo.setText("Undo");
		jMenu1.add(itemUndo);

		itemRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_Y,
				java.awt.event.InputEvent.CTRL_MASK));
		itemRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/redo.png"))); // NOI18N
		itemRedo.setText("Redo");
		jMenu1.add(itemRedo);
		jMenu1.add(jSeparator3);

		itemQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_Q,
				java.awt.event.InputEvent.CTRL_MASK));
		itemQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/quit.png"))); // NOI18N
		itemQuit.setText("Quit");
		jMenu1.add(itemQuit);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("User");

		itemSignup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_U,
				java.awt.event.InputEvent.CTRL_MASK));
		itemSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/signup.png"))); // NOI18N
		itemSignup.setText("SignUp");
		jMenu2.add(itemSignup);

		itemSignin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_I,
				java.awt.event.InputEvent.CTRL_MASK));
		itemSignin.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/signin.png"))); // NOI18N
		itemSignin.setText("SignIn");
		jMenu2.add(itemSignin);

		itemSignOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_X,
				java.awt.event.InputEvent.CTRL_MASK));
		itemSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/signout.png"))); // NOI18N
		itemSignOut.setText("SignOut");
		jMenu2.add(itemSignOut);

		jMenuBar1.add(jMenu2);

		jMenu3.setText("View");

		itemTheme.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_T,
				java.awt.event.InputEvent.ALT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		itemTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/theme.png"))); // NOI18N
		itemTheme.setText("Theme");
		jMenu3.add(itemTheme);

		jMenuBar1.add(jMenu3);

		jMenu6.setText("Option");

		itmDifficulty.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_D,
				java.awt.event.InputEvent.CTRL_MASK));
		itmDifficulty.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/level.png"))); // NOI18N
		itmDifficulty.setText("Difficulty");
		jMenu6.add(itmDifficulty);

		itemRanking.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_R,
				java.awt.event.InputEvent.CTRL_MASK));
		itemRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/ranking.png"))); // NOI18N
		itemRanking.setText("Ranking");
		jMenu6.add(itemRanking);

		jMenuBar1.add(jMenu6);

		jMenu4.setText("Help");

		itemHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_F1, 0));
		itemHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/help.png"))); // NOI18N
		itemHelp.setText("Help");
		jMenu4.add(itemHelp);

		itemRegister.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_R,
				java.awt.event.InputEvent.CTRL_MASK));
		itemRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/register.png"))); // NOI18N
		itemRegister.setText("Register");
		jMenu4.add(itemRegister);

		itemUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_F11, 0));
		itemUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/update.png"))); // NOI18N
		itemUpdate.setText("Check for Update");
		jMenu4.add(itemUpdate);
		jMenu4.add(jSeparator2);

		ItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_F12, 0));
		ItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Icons/aboutus.png"))); // NOI18N
		ItemAbout.setText("About");
		ItemAbout.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ItemAboutActionPerformed(evt);
			}
		});
		jMenu4.add(ItemAbout);

		jMenuBar1.add(jMenu4);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														plTop,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		plCenter,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		plRight,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														jLabel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														237,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(plTop,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														plRight,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														plCenter,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addComponent(jLabel2)
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void formatcell(Cell[][] cell) {
		for (int i = 0; i < ROW; ++i) {
			for (int j = 0; j < COL; ++j) {
				cell[i][j] = new Cell(i, j);
				cell[i][j].setPreferredSize(new Dimension(70, 50));
				cell[i][j].setText(String.valueOf(j));
				cell[i][j].setMargin(new Insets(1, 1, 1, 1));
				cell[i][j].setBackground(Color.YELLOW);
				cell[i][j].setFont(new Font("Serif", Font.BOLD, 24));
				cell[i][j].setForeground(Color.BLACK);
				cell[i][j].setContentAreaFilled(false);
				cell[i][j].setBorder(BorderFactory.createLineBorder(
						Color.DARK_GRAY, 1));
				cell[i][j].setOpaque(true);
			}
		}
	}

	private void ItemAboutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ItemAboutActionPerformed
		// TODO add your handling code here:
		JDialogAbout about = new JDialogAbout(this);
		about.setVisible(true);
	}// GEN-LAST:event_ItemAboutActionPerformed

	public void addActionListener(ActionListener ac) {
		btnNewgame.addActionListener(ac);
		btnLevel.addActionListener(ac);
		btnPause.addActionListener(ac);
		btnBack.addActionListener(ac);
		BtnRedo.addActionListener(ac);
		btnSave.addActionListener(ac);
		btnLoad.addActionListener(ac);
		btnAbout.addActionListener(ac);

	}

	public void addCellActionListener(ActionListener ac) {
		for (int i = 0; i < ROW; ++i) {
			for (int j = 0; j < COL; ++j) {
				cell[i][j].addActionListener(ac);
				formatcell(cell);
			}
		}
	}

	public void showMessage(String msg) {
		JOptionPane.showMessageDialog(this, msg);
	}

	public Cell[][] getArrayCell() {
		return cell;
	}

	public void resetPanelCenter(Cell[][] listCell) {
		for (int i = 0; i < ROW; ++i) {
			for (int j = 0; j < COL; ++j) {
				int number = listCell[i][j].getValue();
				if (number > 0) {
					cell[i][j].setValue(number);
					formatcell(cell);
				}
				if (number <= 0) {
					cell[i][j].resetCell();
					formatcell(cell);
				}
			}
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SudokuView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SudokuView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SudokuView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SudokuView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SudokuView().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BtnRedo;
	private javax.swing.JMenuItem ItemAbout;
	private javax.swing.JButton btnAbout;
	private javax.swing.JButton btnBack;
	private javax.swing.JButton btnLevel;
	private javax.swing.JButton btnLoad;
	private javax.swing.JButton btnNewgame;
	private javax.swing.JButton btnPause;
	private javax.swing.JButton btnRank;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnTheme;
	private javax.swing.JMenuItem itemHelp;
	private javax.swing.JMenuItem itemLoadGame;
	private javax.swing.JMenuItem itemNewGame;
	private javax.swing.JMenuItem itemQuit;
	private javax.swing.JMenuItem itemRanking;
	private javax.swing.JMenuItem itemRedo;
	private javax.swing.JMenuItem itemRegister;
	private javax.swing.JMenuItem itemSaveGame;
	private javax.swing.JMenuItem itemSignOut;
	private javax.swing.JMenuItem itemSignin;
	private javax.swing.JMenuItem itemSignup;
	private javax.swing.JMenuItem itemTheme;
	private javax.swing.JMenuItem itemUndo;
	private javax.swing.JMenuItem itemUpdate;
	private javax.swing.JMenuItem itmDifficulty;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu6;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPopupMenu.Separator jSeparator1;
	private javax.swing.JPopupMenu.Separator jSeparator2;
	private javax.swing.JPopupMenu.Separator jSeparator3;
	private javax.swing.JLabel lbTime;
	private javax.swing.JLabel lbUsername;
	private javax.swing.JPanel plCenter;
	private javax.swing.JPanel plRight;
	private javax.swing.JPanel plTop;
	// End of variables declaration//GEN-END:variables
}
